name: Subs Check
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 */2 * *'

permissions:
  contents: write
  packages: write

jobs:
  BuildAndUpdate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: subs-check   # 指定子目录

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: 设置时区为北京时间
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"

      - name: 创建Go运行环境
        run: |
          go mod tidy
          mkdir -p output
          touch output/once

      - name: 设置配置参数config.yaml
        run: |
          cp config/config.example.yaml config/config.yaml
          sed -i 's/success-limit: 100/success-limit: 150/' config/config.yaml
          sed -i 's/min-speed: 512/min-speed: 1024/' config/config.yaml
          sed -i 's/download-mb: 10/download-mb: 20/' config/config.yaml

      - name: 运行程序并获取YAML文件
        run: |
          go run . -f ./config/config.yaml
          cp output/all.yaml assets/Best.yaml

      - name: 提交更改
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add assets/Best.yaml
          CURRENT_TIME=$(date +"%Y-%m-%d %H:%M:%S")
          git commit -m "Update assets/Best.yaml at $CURRENT_TIME" || echo "No changes"
          git push